### ISSUE TITLE
NTR: Request for S14 blade

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S14#1]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>blade <p><b>Definition</b><p> Term to be used when the property reported is said to relate to biological entities with that specific morphotype.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/S25/issues/34<p>

**Comment by gwemon** [comment]
Term is live on the NVS: http://vocab.nerc.ac.uk/collection/S14/current/S1499/
